#####################################################
# Las tablas de las reglas y los conjuntos de estas #
#####################################################

DROP TABLE IF EXISTS RULES_IN_SETS;
DROP TABLE IF EXISTS RULES_SETS;
DROP TABLE IF EXISTS RULES;

CREATE TABLE RULES_IN_SETS (
	ID_RULE INTEGER UNSIGNED NOT NULL,
	ID_RULE_SET INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (ID_RULE, ID_RULE_SET),
	KEY (ID_RULE),
	KEY (ID_RULE_SET)
);

CREATE TABLE RULES_SETS (
	ID_RULE_SET INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL,
	ACTIVE BOOL NOT NULL,
	PRIMARY KEY (ID_RULE_SET)
);

CREATE TABLE RULES (
	ID_RULE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL,
	RULE TEXT NOT NULL,
	PRIMARY KEY (ID_RULE)
);

ALTER TABLE RULES_IN_SETS ADD CONSTRAINT FK_RULES_IN_SETS_RULES 
	FOREIGN KEY (ID_RULE) REFERENCES RULES (ID_RULE)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RULES_IN_SETS ADD CONSTRAINT FK_RULES_IN_SETS_RULES_SETS 
	FOREIGN KEY (ID_RULE_SET) REFERENCES RULES_SETS (ID_RULE_SET)
	ON DELETE CASCADE ON UPDATE CASCADE;
	
###########################################################
# Las tablas que corresponde a los agentes y las materias #
###########################################################

DROP TABLE IF EXISTS AGENTS_SUBJECTS;
DROP TABLE IF EXISTS SUBJECTS;
DROP TABLE IF EXISTS AGENTS;

CREATE TABLE AGENTS_SUBJECTS (
	ID_AGENT INTEGER UNSIGNED NOT NULL,
	ID_SUBJECT INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (ID_AGENT, ID_SUBJECT),
	KEY (ID_SUBJECT),
	KEY (ID_AGENT)
);

CREATE TABLE SUBJECTS (
	ID_SUBJECT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(75) NOT NULL,
	PRIMARY KEY (ID_SUBJECT)
);

CREATE TABLE AGENTS (
	ID_AGENT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_AGENT)
);

ALTER TABLE AGENTS_SUBJECTS ADD CONSTRAINT FK_AGENTS_SUBJECTS_SUBJECTS 
	FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS (ID_SUBJECT)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE AGENTS_SUBJECTS ADD CONSTRAINT FK_AGENTS_SUBJECTS_AGENTS 
	FOREIGN KEY (ID_AGENT) REFERENCES AGENTS (ID_AGENT)
	ON DELETE CASCADE ON UPDATE CASCADE;
	
###########################################################
###### Las tablas que corresponde a los instrumentos ######
###########################################################
	
DROP TABLE IF EXISTS INSTRUMENTS;
DROP TABLE IF EXISTS FORMAL_INSTRUMENTS;
DROP TABLE IF EXISTS OBJECTIVE_INSTRUMENTS;
DROP TABLE IF EXISTS CORRESPONDENCE_INSTRUMENTS;

CREATE TABLE INSTRUMENTS (
	ID_INSTRUMENT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRIPTION TEXT NOT NULL,
	PRIMARY KEY (ID_INSTRUMENT)
);

CREATE TABLE FORMAL_INSTRUMENTS (
	ID_INSTRUMENT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID_INSTRUMENT)
);

CREATE TABLE OBJECTIVE_INSTRUMENTS (
	ID_INSTRUMENT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID_INSTRUMENT)
);

CREATE TABLE CORRESPONDENCE_INSTRUMENTS (
	ID_INSTRUMENT INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID_INSTRUMENT)
);

ALTER TABLE FORMAL_INSTRUMENTS ADD CONSTRAINT FK_FORMAL_INSTRUMENTS_INSTRUMENTS 
	FOREIGN KEY (ID_INSTRUMENT) REFERENCES INSTRUMENTS (ID_INSTRUMENT)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE OBJECTIVE_INSTRUMENTS ADD CONSTRAINT FK_OBJECTIVE_INSTRUMENTS_FORMAL_INSTRUMENTS
	FOREIGN KEY (ID_INSTRUMENT) REFERENCES FORMAL_INSTRUMENTS (ID_INSTRUMENT)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CORRESPONDENCE_INSTRUMENTS ADD CONSTRAINT FK_CORRESPONDENCE_INSTRUMENTS_OBJECTIVE_INSTRUMENTS 
	FOREIGN KEY (ID_INSTRUMENT) REFERENCES OBJECTIVE_INSTRUMENTS (ID_INSTRUMENT)
	ON DELETE CASCADE ON UPDATE CASCADE;

###########################################################
####### Las tablas que corresponde a las respuestas #######
###########################################################

DROP TABLE IF EXISTS ANSWERS;
DROP TABLE IF EXISTS RELATIONS_ANSWERS;

CREATE TABLE ANSWERS (
	ID_ANSWER INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID_ANSWER)
);

CREATE TABLE RELATIONS_ANSWERS (
	ID_ANSWER INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	LEFT_SIDE VARCHAR(200) NULL,
	RIGHT_SIDE VARCHAR(200) NULL,
	ID_INSTRUMENT INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (ID_ANSWER),
	KEY (ID_INSTRUMENT)
);

ALTER TABLE RELATIONS_ANSWERS ADD CONSTRAINT FK_RELATIONS_ANSWERS_CORRESPONDENCE_INSTRUMENTS 
	FOREIGN KEY (ID_INSTRUMENT) REFERENCES CORRESPONDENCE_INSTRUMENTS (ID_INSTRUMENT)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RELATIONS_ANSWERS ADD CONSTRAINT FK_RELATIONS_ANSWERS_ANSWERS 
	FOREIGN KEY (ID_ANSWER) REFERENCES ANSWERS (ID_ANSWER)
	ON DELETE CASCADE ON UPDATE CASCADE;
	
	

############################################################
############ El script de borrado de las tablas ############
############################################################

DELETE FROM RELATIONS_ANSWERS;
DELETE FROM ANSWERS;
DELETE FROM CORRESPONDENCE_INSTRUMENTS;
DELETE FROM OBJECTIVE_INSTRUMENTS;
DELETE FROM FORMAL_INSTRUMENTS;
DELETE FROM INSTRUMENTS;

############################################################
############################################################
############################################################